#!/usr/bin/env ruby
# frozen_string_literal: true

if File.exist?('config/environment.rb')
  # Load rails env if inside a rails app
  require_relative File.join(Dir.pwd, 'config', 'environment')
elsif File.exist?('Gemfile.lock')
  # Load bundler context if using bundler
  require 'bundler/setup'
end

require 'nagare_redis'

NagareRedis.logger = nil
NagareRedis.logger.level = :info

# TODO: Capture interrupt and wait for listeners to not be busy before shutting
#       down
NagareRedis::ListenerPool.start_listening.join
